repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade

-   repo: local
    hooks:
    -   id: pep8-naming-convention
        name: PEP 8 snake case naming convention
        entry: File and dir names must follow PEP 8 snake case naming convention.
        language: fail
        files: '^(?![_a-z0-9/]+\.py$).*\.py'

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
