repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade

-   repo: local
    hooks:
      -   id: check-python-filenames
          name: Check Python filenames for snake_case
          entry: bash -c 'for f in $(git diff --cached --name-only | grep .py); do filename=$(basename "$f"); if [[ ! $filename =~ ^[a-z_]+\.py$ ]]; then echo "Filename $f does not follow PEP 8 snake_case naming convention"; exit 1; fi; done'
          language: system
          types: [python]