repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade

-   repo: local
    hooks:
      -   id: check-python-filenames
          name: Check Python file and directory names for snake_case
          entry: filenames must be lower-case or lower_case only
          language: fail
          files: '[^a-z0-9._/-]'
